### ISSUE TITLE
Another issue

### ISSUE THREAD

**Issue by GamingPandaz12326** [Edward7s/Nocturnal-V3#3]
Hi, when I put "Nocturnal.sln" in visual studio the references have yellow triangles and I get a few errors.

**Comment by Edward7s** [comment]
Hi u need to add all the references back, why are u trying to open the project in visual studio, u will need to update it yourself every time I push an update if u do that.
Also no offense but I don't recommend you to use Visual Studio to compile the dll science u didn't know how to add the references back and every update u will need to update it your self or get the update's from my Github, In my discord server there is a channel called loader-download, download the dll and drag it into your mods, that will load the Client every time u launch the game so u will get all the newest updates automatically with out needing to edit or do anything.

**Comment by GamingPandaz12326** [comment]
Thanks for the reply, is there a tutorial out there somewhere to help me add the reference back? If not don't worry about it

**Comment by MasterMod22** [comment]
To add references you at melonloader folder and melonloader managed folder by right clicking properties on the cspj whatever it's called and you add it in the references path
