### ISSUE TITLE
player list opacity doesnt save after game restart 

### ISSUE THREAD

**Issue by nixywixy** [Edward7s/Nocturnal-V3#4]
![image](https://user-images.githubusercontent.com/70996036/173641496-cdafcf63-7d3d-49c9-bfc7-d433915a8c30.png)

even when opacity is on 0 it will go back to 100% after game restart

**Comment by Edward7s** [comment]
Did u save the config?

**Comment by nixywixy** [comment]
yeah look at the menu it says .055% which should be damn near invisible and its full opacity

**Comment by Edward7s** [comment]
Alright I will push a update tomorrow and fix the bug.

**Comment by Edward7s** [comment]
Let me know if it fixed your issue.
